"use client";
import Navbar from "../components/Navbar";
import Link from "next/link";
import { AlertTriangle, CheckCircle, ArrowRight, Download } from "lucide-react";

import { useEffect, useState } from "react";

const cls = {
  page: "min-h-screen bg-[#f9f5ef] text-[#1a1008] font-['Inter',sans-serif] selection:bg-[#C0B298] selection:text-[#1a1008]",
  clash: "font-['Space_Grotesk',sans-serif] font-bold tracking-tighter uppercase",
  label: "text-[10px] tracking-[0.4em] text-[#6b5744] uppercase font-bold",
};

interface Obligation {
  id: string;
  clause: string;
  type: string;
  desc: string;
  confidence: number;
  adjustedRisk: number;
}

function RiskBar({ value, status }: { value: number; status: string }) {
  const color = status === "high" ? "bg-red-500" : status === "warning" ? "bg-amber-500" : "bg-emerald-500";
  const bg = status === "high" ? "bg-red-100" : status === "warning" ? "bg-amber-100" : "bg-emerald-100";
  return (
    <div className={`w-full ${bg} rounded-full h-1.5`}>
      <div className={`h-1.5 rounded-full ${color}`} style={{ width: `${value}%` }} />
    </div>
  );
}

export default function ReportPage() {
  const [data, setData] = useState<{
    contractName: string;
    obligations: Obligation[];
    overallRisk: number;
    timeRange: string;
  } | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem("cPulse_report");
    if (saved) {
      try {
        setData(JSON.parse(saved));
      } catch (e) {}
    }
  }, []);

  if (!data) return (
    <div className={cls.page + " pt-40 md:px-12 px-6 flex flex-col items-center"}>
      <Navbar />
      <h2 className={`${cls.clash} text-2xl text-center mb-4`}>No Report Data Available</h2>
      <p className="text-[#1a1008]/50 mb-8">Please analyze a contract on the Demo page first.</p>
      <Link href="/demo" className="bg-[#1a1008] text-[#f9f5ef] px-6 py-3 rounded-full text-sm font-black uppercase tracking-widest hover:bg-[#C0B298] hover:text-[#1a1008] transition-colors">
        Go to Demo
      </Link>
    </div>
  );

  const covenants = data.obligations.map(o => ({
  id: o.id,
  description: o.clause + " - " + o.type,
  // Using the actual model description as the limit/requirement
  limit: o.desc, 
  // Make the 'current' label dynamic based on the risk level
  current: o.adjustedRisk >= 70 ? "At Risk" : o.adjustedRisk >= 40 ? "Approaching Limit" : "Compliant",
  margin: `AI Confidence: ${o.confidence}%`,
  riskPct: o.adjustedRisk,
  status: o.adjustedRisk >= 70 ? "high" : o.adjustedRisk >= 40 ? "warning" : "safe",
  trend: o.adjustedRisk >= 70 ? "↑ worsening" : o.adjustedRisk >= 40 ? "— stable" : "↓ safe",
  actions: o.adjustedRisk >= 70 
    ? ["Requires immediate legal review", "Prepare mitigation strategy for potential breach", "Assess exposure in related facilities"]
    : o.adjustedRisk >= 40
    ? ["Monitor closely in next reporting cycle", "Clarify exact parameters with counsel"]
    : ["No immediate action needed", "Standard compliance check required"],
  // Pass the actual obligation text as the context driver
  drivers: ["Extracted Requirement: " + (o.desc.length > 80 ? o.desc.substring(0, 80) + "..." : o.desc)]
}));

  const highRisk    = covenants.filter(c => c.status === "high").length;
  const warningRisk = covenants.filter(c => c.status === "warning").length;
  const avgRisk     = data.overallRisk;

  return (
    <div className={cls.page}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@600;700;900&family=Inter:wght@400;500;700&display=swap');`}</style>
      <Navbar />

      <div className="pt-28 pb-20 px-6 md:px-12">
        <div className="max-w-5xl mx-auto">

          {/* Report header */}
          <div className="flex flex-col md:flex-row justify-between items-start mb-12 gap-6 pb-12 border-b-2 border-[#1a1008]/10">
            <div>
              <p className={cls.label}>Covenant Risk Report · Confidential</p>
              <h1 className={`${cls.clash} text-[clamp(2rem,5vw,4rem)] leading-tight mt-3 mb-2`}>{data.contractName.toUpperCase() || "CONTRACT ANALYSIS"}</h1>
              <p className="text-sm text-[#6b5744]">Generated by ContractPulse · Live AI Analysis</p>
            </div>
            <div className="flex gap-3 flex-wrap print:hidden">
              <button onClick={() => window.print()} className="flex items-center gap-2 border-2 border-[#1a1008] text-[#1a1008] px-5 py-2.5 rounded-full text-xs font-black uppercase tracking-widest hover:bg-[#1a1008] hover:text-[#f9f5ef] transition-colors">
                <Download size={14} /> Export PDF
              </button>
              <Link href="/dashboard" className="bg-[#1a1008] text-[#f9f5ef] px-5 py-2.5 rounded-full text-xs font-black uppercase tracking-widest hover:bg-[#C0B298] hover:text-[#1a1008] transition-colors">
                Back to Dashboard
              </Link>
            </div>
          </div>

          {/* Risk summary band */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
            {[
              { label: "Overall Risk Score", val: `${avgRisk}%`,         accent: avgRisk >= 60 },
              { label: "High Risk Covenants", val: `${highRisk}`,        accent: highRisk > 0 },
              { label: "Warning Covenants",   val: `${warningRisk}` },
              { label: "Time-to-Breach", val: data.timeRange, accent: true },
            ].map((s) => (
              <div key={s.label} className={`p-6 rounded-2xl border-2 ${s.accent ? "border-red-400 bg-red-50" : "border-[#1a1008]/10 bg-white"}`}>
                <p className="text-[10px] tracking-widest uppercase font-bold text-[#6b5744] mb-2">{s.label}</p>
                <p className={`font-['Space_Grotesk',sans-serif] font-bold text-3xl ${s.accent ? "text-red-600" : "text-[#1a1008]"}`}>{s.val}</p>
              </div>
            ))}
          </div>

          {/* Executive Summary */}
          <div className="bg-white border-2 border-[#1a1008]/10 rounded-2xl p-8 mb-8">
  <h2 className={`${cls.clash} text-xl mb-4`}>Executive Summary</h2>
  <p className="text-sm leading-relaxed text-[#1a1008]/70 mb-4">
    The obligation profile for <strong className="text-[#1a1008]">{data.contractName || "the analyzed contract"}</strong> presents an overall risk score of <strong className={data.overallRisk >= 70 ? "text-red-600" : data.overallRisk >= 40 ? "text-amber-600" : "text-emerald-600"}>{data.overallRisk}%</strong>. 
    {data.overallRisk >= 70 ? " This indicates elevated exposure requiring immediate review." : data.overallRisk >= 40 ? " This indicates moderate exposure; monitoring is advised." : " This indicates a safe compliance margin."}
  </p>
  {data.timeRange !== "—" && (
    <p className="text-sm leading-relaxed text-[#1a1008]/70">
      Based on the scenario parameters set during analysis, the estimated time-to-breach window is <strong className="text-[#1a1008]">{data.timeRange}</strong>.
    </p>
  )}
</div>

          {/* Covenant deep-dives */}
          <h2 className={`${cls.clash} text-2xl mb-6`}>Covenant-Level Analysis</h2>
          <div className="space-y-6 mb-12">
            {covenants.map((cov) => (
              <div key={cov.id} className={`bg-white border-2 rounded-2xl overflow-hidden ${cov.status === "high" ? "border-red-400" : cov.status === "warning" ? "border-amber-400" : "border-[#1a1008]/10"}`}>
                {/* Header bar */}
                <div className={`px-8 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4 ${cov.status === "high" ? "bg-red-50" : cov.status === "warning" ? "bg-amber-50" : "bg-emerald-50"}`}>
                  <div>
                    <p className="text-[10px] text-[#6b5744] tracking-widest uppercase font-bold mb-1">{cov.id}</p>
                    <h3 className={`${cls.clash} text-base`}>{cov.description}</h3>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Current</p>
                      <p className="font-bold text-lg">{cov.current}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Limit</p>
                      <p className="font-bold text-lg">{cov.limit}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Risk</p>
                      <p className={`font-bold text-lg ${cov.status === "high" ? "text-red-600" : cov.status === "warning" ? "text-amber-600" : "text-emerald-600"}`}>{cov.riskPct}%</p>
                    </div>
                  </div>
                </div>

                <div className="px-8 py-6">
                  {/* Risk bar */}
                  <div className="mb-6">
                    <div className="flex justify-between text-xs text-[#6b5744] mb-2">
                      <span>{cov.margin}</span>
                      <span className="font-semibold">{cov.trend}</span>
                    </div>
                    <RiskBar value={cov.riskPct} status={cov.status} />
                  </div>

                  {cov.drivers.length > 0 && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div>
                        <p className="text-[10px] tracking-widest font-bold uppercase text-[#6b5744] mb-3 flex items-center gap-2">
                          <AlertTriangle size={12} /> Key Drivers
                        </p>
                        <div className="space-y-2">
                          {cov.drivers.map((d) => (
                            <div key={d} className="flex items-start gap-2 text-sm text-[#1a1008]/70">
                              <ArrowRight size={12} className="mt-0.5 shrink-0 text-amber-600" /> {d}
                            </div>
                          ))}
                        </div>
                      </div>
                      <div>
                        <p className="text-[10px] tracking-widest font-bold uppercase text-[#6b5744] mb-3 flex items-center gap-2">
                          <CheckCircle size={12} className="text-emerald-600" /> Recommended Actions
                        </p>
                        <div className="space-y-2">
                          {cov.actions.map((a) => (
                            <div key={a} className="flex items-start gap-2 text-sm text-[#1a1008]/70">
                              <ArrowRight size={12} className="mt-0.5 shrink-0 text-emerald-600" /> {a}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                  {cov.drivers.length === 0 && (
                    <p className="text-sm text-emerald-700 flex items-center gap-2"><CheckCircle size={14} /> No immediate risk. Covenant is tracking well within limits.</p>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="border-t-2 border-[#1a1008]/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
            <div>
              <p className="text-xs text-[#6b5744]">Generated by ContractPulse v2.4 · Confidential · Not for distribution</p>
              <p className="text-xs text-[#6b5744] mt-1">Based on management accounts. AI-assisted extraction — verify with legal counsel before acting.</p>
            </div>
            <div className="text-right">
              <p className={`${cls.clash} text-sm text-[#1a1008]`}>CONTRACTPULSE</p>
              <p className="text-xs text-[#6b5744]">contractpulse.in</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
