"use client";
import Navbar from "../components/Navbar";
import Link from "next/link";
import { AlertTriangle, CheckCircle, ArrowRight, Download } from "lucide-react";

const cls = {
  page: "min-h-screen bg-[#f9f5ef] text-[#1a1008] font-['Inter',sans-serif] selection:bg-[#C0B298] selection:text-[#1a1008]",
  clash: "font-['Space_Grotesk',sans-serif] font-bold tracking-tighter uppercase",
  label: "text-[10px] tracking-[0.4em] text-[#6b5744] uppercase font-bold",
};

const covenants = [
  {
    id: "C1",
    description: "Debt/EBITDA ≤ 3.5x",
    current: "2.9x",
    limit: "3.5x",
    margin: "0.6x headroom",
    riskPct: 74,
    status: "warning",
    trend: "↑ worsening",
    ttb: "36–52 days",
    drivers: ["Revenue declined 8% QoQ", "EBITDA margin compressed by rising input costs", "Short-term debt refinanced at higher principal"],
    actions: ["Pursue cost reduction of ₹30–40L/quarter", "Consider early repayment of higher-interest facilities", "Pre-emptively discuss covenant waiver with SBI"],
  },
  {
    id: "C2",
    description: "Minimum Cash Balance ≥ ₹50L",
    current: "₹61L",
    limit: "₹50L",
    margin: "₹11L headroom",
    riskPct: 51,
    status: "warning",
    trend: "↓ stable",
    ttb: "58–74 days",
    drivers: ["Cash burn elevated due to capex spend", "Receivables collection cycle extended by 12 days"],
    actions: ["Accelerate receivables collection", "Defer discretionary capex by one quarter"],
  },
  {
    id: "C3",
    description: "Interest Coverage Ratio (ICR) ≥ 1.5x",
    current: "1.62x",
    limit: "1.5x",
    margin: "0.12x headroom",
    riskPct: 88,
    status: "high",
    trend: "↑ deteriorating fast",
    ttb: "11–18 days",
    drivers: ["Rising interest rates increasing debt servicing cost", "Declining operating profit margin", "New facility drawdown increasing interest burden"],
    actions: ["Immediately reduce interest-bearing debt", "Raise equity or mezzanine capital to improve ratio", "Alert CFO and prepare lender communication for potential breach"],
  },
  {
    id: "C4",
    description: "Quarterly reporting within 45 days of quarter end",
    current: "On track",
    limit: "45 days",
    margin: "14 days remaining",
    riskPct: 10,
    status: "safe",
    trend: "— on track",
    ttb: "N/A",
    drivers: [],
    actions: ["File accounts by Q3 deadline", "No action required"],
  },
];

function RiskBar({ value, status }: { value: number; status: string }) {
  const color = status === "high" ? "bg-red-500" : status === "warning" ? "bg-amber-500" : "bg-emerald-500";
  const bg = status === "high" ? "bg-red-100" : status === "warning" ? "bg-amber-100" : "bg-emerald-100";
  return (
    <div className={`w-full ${bg} rounded-full h-1.5`}>
      <div className={`h-1.5 rounded-full ${color}`} style={{ width: `${value}%` }} />
    </div>
  );
}

export default function ReportPage() {
  const highRisk    = covenants.filter(c => c.status === "high").length;
  const warningRisk = covenants.filter(c => c.status === "warning").length;
  const avgRisk     = Math.round(covenants.reduce((a, c) => a + c.riskPct, 0) / covenants.length);

  return (
    <div className={cls.page}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@600;700;900&family=Inter:wght@400;500;700&display=swap');`}</style>
      <Navbar />

      <div className="pt-28 pb-20 px-6 md:px-12">
        <div className="max-w-5xl mx-auto">

          {/* Report header */}
          <div className="flex flex-col md:flex-row justify-between items-start mb-12 gap-6 pb-12 border-b-2 border-[#1a1008]/10">
            <div>
              <p className={cls.label}>Covenant Risk Report · Confidential</p>
              <h1 className={`${cls.clash} text-[clamp(2rem,5vw,4rem)] leading-tight mt-3 mb-2`}>ACME CORP —<br />SBI TERM LOAN</h1>
              <p className="text-sm text-[#6b5744]">Generated by ContractPulse · April 24, 2026 · As of: Q1 FY26</p>
            </div>
            <div className="flex gap-3 flex-wrap print:hidden">
              <button onClick={() => window.print()} className="flex items-center gap-2 border-2 border-[#1a1008] text-[#1a1008] px-5 py-2.5 rounded-full text-xs font-black uppercase tracking-widest hover:bg-[#1a1008] hover:text-[#f9f5ef] transition-colors">
                <Download size={14} /> Export PDF
              </button>
              <Link href="/dashboard" className="bg-[#1a1008] text-[#f9f5ef] px-5 py-2.5 rounded-full text-xs font-black uppercase tracking-widest hover:bg-[#C0B298] hover:text-[#1a1008] transition-colors">
                Back to Dashboard
              </Link>
            </div>
          </div>

          {/* Risk summary band */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
            {[
              { label: "Overall Risk Score", val: `${avgRisk}%`,         accent: avgRisk >= 60 },
              { label: "High Risk Covenants", val: `${highRisk}`,        accent: highRisk > 0 },
              { label: "Warning Covenants",   val: `${warningRisk}` },
              { label: "Time-to-Breach (Worst Case)", val: "11–18 days", accent: true },
            ].map((s) => (
              <div key={s.label} className={`p-6 rounded-2xl border-2 ${s.accent ? "border-red-400 bg-red-50" : "border-[#1a1008]/10 bg-white"}`}>
                <p className="text-[10px] tracking-widest uppercase font-bold text-[#6b5744] mb-2">{s.label}</p>
                <p className={`font-['Space_Grotesk',sans-serif] font-bold text-3xl ${s.accent ? "text-red-600" : "text-[#1a1008]"}`}>{s.val}</p>
              </div>
            ))}
          </div>

          {/* Executive Summary */}
          <div className="bg-white border-2 border-[#1a1008]/10 rounded-2xl p-8 mb-8">
            <h2 className={`${cls.clash} text-xl mb-4`}>Executive Summary</h2>
            <p className="text-sm leading-relaxed text-[#1a1008]/70 mb-4">
              As of Q1 FY26, Acme Corp's obligation profile under the SBI Term Loan Agreement presents <strong className="text-red-600">elevated breach risk</strong> on the Interest Coverage Ratio (ICR) covenant. The ICR stands at 1.62x against a 1.5x floor — a margin of only 0.12x. At the current trajectory (declining operating margins + rising interest expense), breach is projected within <strong className="text-red-600">11–18 days</strong>.
            </p>
            <p className="text-sm leading-relaxed text-[#1a1008]/70">
              The Debt/EBITDA covenant is under watch (0.6x headroom, deteriorating trend). Minimum cash balance is within range but narrowing. Reporting covenant is on track.
            </p>
          </div>

          {/* Covenant deep-dives */}
          <h2 className={`${cls.clash} text-2xl mb-6`}>Covenant-Level Analysis</h2>
          <div className="space-y-6 mb-12">
            {covenants.map((cov) => (
              <div key={cov.id} className={`bg-white border-2 rounded-2xl overflow-hidden ${cov.status === "high" ? "border-red-400" : cov.status === "warning" ? "border-amber-400" : "border-[#1a1008]/10"}`}>
                {/* Header bar */}
                <div className={`px-8 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4 ${cov.status === "high" ? "bg-red-50" : cov.status === "warning" ? "bg-amber-50" : "bg-emerald-50"}`}>
                  <div>
                    <p className="text-[10px] text-[#6b5744] tracking-widest uppercase font-bold mb-1">{cov.id}</p>
                    <h3 className={`${cls.clash} text-base`}>{cov.description}</h3>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Current</p>
                      <p className="font-bold text-lg">{cov.current}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Limit</p>
                      <p className="font-bold text-lg">{cov.limit}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-[#6b5744] uppercase tracking-widest">Risk</p>
                      <p className={`font-bold text-lg ${cov.status === "high" ? "text-red-600" : cov.status === "warning" ? "text-amber-600" : "text-emerald-600"}`}>{cov.riskPct}%</p>
                    </div>
                  </div>
                </div>

                <div className="px-8 py-6">
                  {/* Risk bar */}
                  <div className="mb-6">
                    <div className="flex justify-between text-xs text-[#6b5744] mb-2">
                      <span>{cov.margin}</span>
                      <span className="font-semibold">{cov.trend}</span>
                    </div>
                    <RiskBar value={cov.riskPct} status={cov.status} />
                  </div>

                  {cov.drivers.length > 0 && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div>
                        <p className="text-[10px] tracking-widest font-bold uppercase text-[#6b5744] mb-3 flex items-center gap-2">
                          <AlertTriangle size={12} /> Key Drivers
                        </p>
                        <div className="space-y-2">
                          {cov.drivers.map((d) => (
                            <div key={d} className="flex items-start gap-2 text-sm text-[#1a1008]/70">
                              <ArrowRight size={12} className="mt-0.5 shrink-0 text-amber-600" /> {d}
                            </div>
                          ))}
                        </div>
                      </div>
                      <div>
                        <p className="text-[10px] tracking-widest font-bold uppercase text-[#6b5744] mb-3 flex items-center gap-2">
                          <CheckCircle size={12} className="text-emerald-600" /> Recommended Actions
                        </p>
                        <div className="space-y-2">
                          {cov.actions.map((a) => (
                            <div key={a} className="flex items-start gap-2 text-sm text-[#1a1008]/70">
                              <ArrowRight size={12} className="mt-0.5 shrink-0 text-emerald-600" /> {a}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                  {cov.drivers.length === 0 && (
                    <p className="text-sm text-emerald-700 flex items-center gap-2"><CheckCircle size={14} /> No immediate risk. Covenant is tracking well within limits.</p>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="border-t-2 border-[#1a1008]/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
            <div>
              <p className="text-xs text-[#6b5744]">Generated by ContractPulse v2.4 · Confidential · Not for distribution</p>
              <p className="text-xs text-[#6b5744] mt-1">Based on management accounts. AI-assisted extraction — verify with legal counsel before acting.</p>
            </div>
            <div className="text-right">
              <p className={`${cls.clash} text-sm text-[#1a1008]`}>CONTRACTPULSE</p>
              <p className="text-xs text-[#6b5744]">contractpulse.in</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
